### ISSUE TITLE
Doesn't effect youtube comments

### ISSUE THREAD

**Issue by farrellit** [Blumed/weblibbs#2]
Youtube comments aren't affected.

<b>Commit:</b> 009ba245
#### Steps to reproduce:
1. turn on extension
2. navigate to youtube.com
3. load a video page
4. try to change one of the words in the comment section
#### Expected Result

words should have changed in comment section
#### Actual Result

"main" webpage shows the word replacement, but it isn't replaced in any of the comments.

**Comment by farrellit** [comment]
http://stackoverflow.com/questions/8917593/do-chrome-extensions-access-iframes seems to have solution?

**Comment by Blumed** [comment]
commit: 7f20901
Hey this fixed it

**Comment by farrellit** [comment]
yeah, totally works
